# Generated by Django 4.0.3 on 2022-08-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_body_note_description_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='body',
        ),
    ]
